### PR TITLE
implemented repeat as a tristate

### PR DESCRIPTION
**Pull request by ColdFireIce**
I tried to follow you're style and implemented repeat as an integer with 3 states.
It should be fallback compatible as 
true == 1 == REPEAT_ALL
and 
false == 0 == NORMAL aka. NOREPEAT
2 == REPEAT_ONE

Greetings

### CODE REVIEW

**Comment by ColdFireIce** [comment]
When currentPlayMode was REPEAT_ALL shuffle would be recognized as true because it was compared with SHUFFLE (3) and not SHUFFLE_NOREPEAT (2).

**Comment by ColdFireIce** [comment]
should this use human readable values as well? this would make the fallback not work anymore.

**Comment by jishi** [comment]
No, I have actually implemented this as a bit flag (since SHUFFLE includes REPEAT_ALL, but REPEAT_NOSHUFFLE does not). I need to investigate how the REPEAT_ONE behaves, I think we need to come up with something clever here.

**Comment by ColdFireIce** [comment]
Well it stills works this way:
repeat_one = 4
shuffle = 2
repeat = 1

but as repeat and repeat_one are mutual exclusive 7 can't occur. 

btw. 672ff46 is independent from that. its just a bug.

**Comment by jishi** [comment]
Yeah, maybe makes sense to have a separate flag for one/all, so:

repeat: 1
shuffle: 2
all/one: 4

**Comment by ColdFireIce** [comment]
so this would be represented as?:
```
NORMAL = {
    repeat: false,
    repeatAll: true, // not used???
    shuffle: false,
    crossfade: false
}

SHUFFLE_REPEAT_ONE = {
    repeat: true,
    repeatAll: false,
    shuffle: true,
    crossfade: false
}
```

**Comment by jishi** [comment]
It can still be represented with a tri-state, the flags are only internal. 

Aha, now I get what you meant bu human readable :) Yeah, maybe it would be human readable but backward compatible with boolean flags.

**Comment by ColdFireIce** [comment]
The current pull request makes the repeat attribute of the playMode an integer with the fallback that makes REPEAT_ALL, REPEAT_ONE and SHUFFLE_REPEAT_ONE evaluate to true (1 and 2) and everything else to false (0):

```
NORMAL = {
    repeat: 0,
    shuffle: false,
    crossfade: false
}
REPEAT_ALL = {
    repeat: 1,
    shuffle: false,
    crossfade: false
}
SHUFFLE_REPEAT_ONE = {
    repeat: 2,
    shuffle: true,
    crossfade: false
}
```
What my question was: should it report something like this to be more human readable:
```
NORMAL = {
    repeat: 'none',
    shuffle: false,
    crossfade: false
}
REPEAT_ALL = {
    repeat: 'all',
    shuffle: false,
    crossfade: false
}
SHUFFLE_REPEAT_ONE = {
    repeat: 'one',
    shuffle: true,
    crossfade: false
}
```

**Comment by jishi** [comment]
Yeah, I guess that makes sense, and also supports these values when setting repeat state.

**Comment by ColdFireIce** [comment]
```
const REPEAT_MODE = Object.freeze({
  NONE: 0,
  ALL: 1,
  ONE: 2
});
```
You could still create an enum to map those values

**Comment by ColdFireIce** [comment]
So... I'm confused now. Which method would you like me to implement?

**Comment by jishi** [comment]
use human readable enum values, but keep support for boolean flag (false = none, true = all)

**Comment by ColdFireIce** [comment]
Ok. But this will only create a fallback for **setting** the repeat mode with Player.repeat().
Any program that **reads** the Player.state.playMode.repeat will then evaluate this to true?
I mean, its still beta so I guess that would be ok?

**Comment by jishi** [comment]
Yeah, it is fine. The most important feature is that the state format should match what is expected in the preset format. And as you said, it is still beta :)

**Comment by ColdFireIce** [comment]
is there something left to do here?

**Comment by jishi** [comment]
I'll try it out first before I merge, I am not 100% sure what your changes do. But I think there is room for improvement on how it handles state in general, since we've had some discrepancies in the anticipated state vs real state.

**Comment by ColdFireIce** [comment]
Since this blocks my master-branch, i'll create a new pull request from a different branch

**Pull request closed without merging**
