### PR TITLE
Update Player.js

### PR DESCRIPTION
**Pull request by jplourde5**
Fixes exception that is thrown due the type being line_in and not having the albumArtUri parameter

### CODE REVIEW

**Comment by jishi** [comment]
I don't think this is still an issue?

**Comment by jplourde5** [comment]
I believe that it is still a problem without the fix. Players on line-in are missing the variable that is being checked.

**Comment by jishi** [comment]
But how do I reproduce it? I use line-in all the time and I don't have any issues?

**Comment by jishi** [comment]
Aha, no wait, I changed the conditional to this: 
`if (state.currentTrack.albumArtUri && state.currentTrack.albumArtUri.startsWith('http'))`

which mitigates this.

**Comment by jplourde5** [comment]
It was probably 2 weeks ago when I did a full install, so if you did this upstream, it may be fixed.  It was a nuisance error that would show only when you started the service.  I don't think that it really hurt anything.  I'll let you know if I see it again the next time I do a full install.

**Pull request closed without merging**
