### PR TITLE
Add Track Number to Browse Item Results

### PR DESCRIPTION
**Pull request by jplourde5**
Allows tracks from the music library to be sorted in album order when playing an album

### CODE REVIEW

**Comment by jishi** [comment]
What exactly is originaltracknumber? 

I would like to see property called `trackNumber` to be consistent, or if the "original" has some relevance, maybe `originalTrackNumber` I assume you have some dependant code for this so it needs to be changed accordingly?

**Comment by jplourde5** [comment]
It is the album track order for everything that I have seen. My guess is that original has meaning in a compilation album, but maybe not even there.  I tested some greatest hits albums and the songs still came out in the right order.  What would you like me to name it?  Yes, I would need to make a quick and minor adjustment to the musicSearch code in the pull request.

**Comment by jishi** [comment]
So are you saying that it is track number for the album name it is listed as? Or tracknumber in an original album (if part of a compilation?)

**Comment by jplourde5** [comment]
The name "original" "seems" to imply the track number from the original album, but the behavior is that it is the track number for the album name.

**Pull request merged**
