### PR TITLE
Invoke returns result object

### PR DESCRIPTION
**Pull request by ColdFireIce**
This change makes it so that soap.invoke, and so every command returns the result as an object rather than an stream.

This makes it easy to do things like "append and play" because the new 1st element index is returned.

### CODE REVIEW

**Comment by jishi** [comment]
Hm, there will be a it of unnecessary overhead to always parse the result for every request like this. For most invocations, we don't care about the result and for those that we care about, you have the stream so you can parse it for those actions only. For which actions are this relevant? AddUriToQueue i guess, anything else?

**Comment by ColdFireIce** [comment]
Yeah, AddUriToQueue is for what I used it. I thought it would be good to centralize the parsing. So there's no code copys for all functions that need the result. (getPositionInfo, browse and AddUriToQueue). could we make it a helper function? I would love to have the parsing of a stream within the project. It would be nice not have to include someting like xml-flow to parse this data in a project that uses sonos-node-discovery

**Comment by jishi** [comment]
Yeah, but all requests will respond with different XML, and you might want to parse them differently. From your example files, seems like you basically put the soap body as xml text, as the result-property? 

It you only want the actual index of the tracks added, you might very well just find that actual XML node and return that, which would reduce the memory overhead significantly, as well as keeping it simple. One could of course try to abstract the xml-flow code somewhat, but you still need to specify which nodes it should act upon, so for this case, it might make more sense to do a helper that act upon queue responses (if this will be duplicated somewhere). There is an AddMultipleUriToQueue action as well, but I think the response is a bit different, and it isn't implemented here yet.

**Comment by ColdFireIce** [comment]
The Code basically turns the content of the request response (1st and only element in the s:body) into an object. sub stream like results or items stay as they are and have to be processed individually.
I think about putting the parsing code into a sperate function within the soap file, so you could do ```soap.invoke().then(soap.parse).then(obj => {//do something})``` if you need it?

**Comment by jishi** [comment]
Okay, having it optional sounds more sane. Just be aware that xml -> js object sometimes doesn't do what you expect it to do, since those two data objects doesn't always have corresponding data trees :)

**Comment by ColdFireIce** [comment]
Yeah that's why I think its ok if you only convert the top-level elements of the response and ignore attributes. As far as I can tell, these are only used for namespaces anyway.

**Comment by ColdFireIce** [comment]
Ok, to avoid the commit revert and merge troubles i'll delete this branch an reopen an new request.

**Pull request closed without merging**
