### PR TITLE
Fix for rogue/non-Sonos upnp device

### PR DESCRIPTION
**Pull request by jplourde5**
This fixed my problem.  I'm now able to debug appleMusic.js.

### CODE REVIEW

**Comment by jishi** [comment]
whaaat? What device is part of the topology but lacks an uuid or a location attribute??

**Comment by jishi** [comment]
I really don't think this is the correct fix. I would love to get an output of the XML or the JSON generated when a topology notification is evented.

**Comment by jplourde5** [comment]
No idea what it is.  I have a number of the old Connect 80’s, original Play 5, new Conect Amp, Playbar, Woofer,  2 Play1’s as surrounds,  and a Play3.  I also have Samsung TV’s, DirecTV boxes, and eero routers, all which may be responding to upnp.  What I was seeing was that one of the members returning in the list had an undefined uuid.  I really didn’t dig any deeper into it.


[cid:image001.gif@01D1B697.3FF1C060]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jplourde5** [comment]
Okay, let me get the appleMusic working and then I’ll pivot to seeing if I can get more info on what this strange member is.


[cid:image001.gif@01D1B698.0625F490]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jishi** [comment]
I had an idea, if you could test the latest master branch of sonos-discovery on your system, let me now how it goes

**Comment by jplourde5** [comment]
Your latest update fixed the "rogue" satellite problem.  Thanks.

**Pull request closed without merging**
